name: 'Test service-jehlomat'

on:
  pull_request:
    paths:
      - 'service-jehlomat/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Run unit tests'
        env:
          DATABASE_HOST: ${{ secrets.$DATABASE_HOST }}
          DATABASE_PORT: ${{ secrets.$DATABASE_PORT }}
          DATABASE_USERNAME: ${{ secrets.$DATABASE_USERNAME }}
          PGPASSWORD: ${{ secrets.$DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.$DATABASE_NAME }}
        run: |
          psql -h $DATABASE_HOST -p $DATABASE_PORT -U $DATABASE_USERNAME -d $DATABASE_NAME -f .service-jehlomat/src/main/resources/create_table.sql
          ./gradlew service-jehlomat:test --no-daemon
