name: 'Deploy web-jehlomat to S3'

on:
  push:
    branches:
      - master
    paths:
      - 'web-jehlomat/**'
env:
  bucket: ${{ secrets.WEB_JEHLOMAT_DEVELOPMENT_BUCKET_NAME }}
  cloudFrontDeploymentId: ${{ secrets.AWS_CLOUDFRONT_DEVELOPMENT_DEPLOYMENT_ID }}
  name: 'web-jehlomat'
  GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Gradle build'
        run: |
          ./gradlew ${{ env.name }}:browserProductionWebpack --no-daemon
      - name: 'Deploy to AWS'
        run: |
          aws s3 sync --sse --delete . s3://${{ env.bucket }}
          aws cloudfront create-invalidation --distribution-id ${{ env.cloudFrontDeploymentId }} --paths "/*"
        working-directory: ${{ env.name }}/build/distributions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'
